---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: kontinu-go
  labels:
    name: kontinu-go
spec:
  #? deployment
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1

  replicas: 1
  selector:
    matchLabels: #! && (AND)
      app: kontinu-go
  template:
    #* pod template
    metadata:
      labels:
        app: kontinu-go
    spec:
      containers:
      - name: kontinu-go
        env:
          - name: FOO
            value: "Hello From K8s ⌛"
        image: kontinu/go-expert:v1.0
        livenessProbe:
          httpGet:
            path: /health
            port: http
          initialDelaySeconds: 60
          timeoutSeconds: 10

        readinessProbe:
          httpGet:
            path: /health
            port: http
          initialDelaySeconds: 5
          timeoutSeconds: 10
        resources:
          limits:
            memory: "500Mi"
            cpu: "500m"
          requests:
            memory: "50Mi"
            cpu: "100m"
        ports:
        - name: http
          containerPort: 8080
...
---
kind: Service
apiVersion: v1
metadata:
  name:  kontinu-go
  annotations:
    description: "go"

spec:
  selector:
    app: kontinu-go
  type:  LoadBalancer
  ports:
  - name:  http
    port:  80
    targetPort:  http
...
