---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: kontinu-menu
  labels:
    name: kontinu-menu
spec:
  #? deployment
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1

  replicas: 1
  selector:
    matchLabels: #! && (AND)
      app: kontinu-menu
  template:
    #* pod template
    metadata:
      labels:
        app: kontinu-menu
    spec:
      containers:
      - name: kontinu-menu
        env:
          - name: FOO
            value: "Hello From K8s ⌛"
        image: kontinu/nginx-expert:v1.0
        # livenessProbe:
        #   httpGet:
        #     path: /health
        #     port: http
        #   initialDelaySeconds: 60
        #   timeoutSeconds: 10

        # readinessProbe:
        #   httpGet:
        #     path: /health
        #     port: http
        #   initialDelaySeconds: 5
        #   timeoutSeconds: 10
        resources:
          limits:
            memory: "500Mi"
            cpu: "500m"
          requests:
            memory: "50Mi"
            cpu: "100m"
        ports:
        - name: http
          containerPort: 80
...
---
kind: Service
apiVersion: v1
metadata:
  name:  kontinu-menu
  annotations:
    description: "mi servicio"

spec:
  selector:
    app: kontinu-menu
  type:  LoadBalancer
  ports:
  - name:  http
    port:  80
    targetPort:  http
...
