---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: kontinu-nodejs
  labels:
    name: kontinu-nodejs
spec:
  #? deployment
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1

  replicas: 3
  selector:
    matchLabels: #! && (AND)
      app: kontinu-nodejs
  template:
    #* pod template
    metadata:
      labels:
        app: kontinu-nodejs
    spec:
      containers:
      - name: kontinu-nodejs
        env:
          - name: FOO
            value: "Hello From K8s ⌛"
          # - name: NEXT_URL
          #   value: "http://kontinu-go/api"
        image: kontinu/nodejs-expert:v1.0
        livenessProbe:
          httpGet:
            path: /health
            port: http
          initialDelaySeconds: 60
          timeoutSeconds: 10

        readinessProbe:
          httpGet:
            path: /health
            port: http
          initialDelaySeconds: 5
          timeoutSeconds: 10
        resources:
          limits:
            memory: "500Mi"
            cpu: "500m"
          requests:
            memory: "50Mi"
            cpu: "10m"
        ports:
        - name: http
          containerPort: 8080
...
---
kind: Service
apiVersion: v1
metadata:
  name:  kontinu-nodejs
  annotations:
    description: "nodejs"

spec:
  selector:
    app: kontinu-nodejs
  type:  LoadBalancer
  ports:
  - name:  http
    port:  80
    targetPort:  http
...
